# Dependencies
markdown:         kramdown
highlighter:      Rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist 
  - jekyll-sitemap
  - jekyll-redirect-from

# Permalinks
permalink:        pretty

# Page and Project organization
include:
  - _pages

collections:
  projects:
    output: true
    permalink: /projects/:slug/


# Setup
title:            Joshua Zhong
tagline:          Tagline_from_config_yaml
description:      Description_from_config_yaml
url:              https://jzhong01.github.io
baseurl:          /my-portfolio

author:
  name:           'Joshua Zhong'
  url:            https://linkedin.com/in/jy-z

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/JZhong01/my-portfolio
